---
sudo: required
dist: xenial

language: c

addons:
  apt:
    packages:
    - python-docutils
    - libmhash-dev
    - python-sphinx

before_install:
  - set -e
  - wget $VARSNIH_TGZ
  - tar -zxf varnish-*.tgz
  - pushd varnish-*/
  - ./configure --prefix=/usr
  - make -sj32
  - sudo make install
  - popd

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

env:
  - VARSNIH_TGZ=https://github.com/varnishcache/varnish-cache/archive/master.tar.gz
  - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.2.0.tgz

script:
  - make check -j4

compiler:
  - clang
  - gcc

allow_failures: VARSNIH_TGZ=https://github.com/varnishcache/varnish-cache/archive/master.tar.gz
